# Generated by Django 3.2.5 on 2021-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
