# Generated by Django 3.2.5 on 2021-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210811_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodelb',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='comment1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='comment2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='comment3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='imgAfter',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='imgBefore',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='sel1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='sel2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientmodelb',
            name='sel3',
            field=models.CharField(max_length=100),
        ),
    ]
